{
 "title": "Ceph",
 "description": "Ceph Cluster Monitor",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ceph_mon_quorum_status, job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_health_status{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_mon_quorum_status{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_pool_bytes_used{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"$job\"}/ceph_cluster_total_bytes{job=\"$job\"}"
    }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_in{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{job=\"$job\"}) - count(ceph_osd_in{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceph_osd_up{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{job=\"$job\"} == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "Agerage PGs per OSD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_numpg{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average OSD Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average OSD Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Average Monitor Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ceph_paxos_refresh_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_paxos_refresh_latency_count{job=\"$job\"}[1m])),1)"
    }
   ]
  },
  { "title": "CLUSTER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{job=\"$job\"}-ceph_cluster_total_used_bytes{job=\"$job\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "ceph_cluster_total_used_bytes{job=\"$job\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "ceph_cluster_total_bytes{job=\"$job\"}",
     "legendFormat": "Total Capacity"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(ceph_osd_op_r{job=\"$job\"}[$interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(ceph_osd_op_w{job=\"$job\"}[$interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(rate(ceph_osd_op_rw{job=\"$job\"}[$interval]))",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{job=\"$job\"}[$interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{job=\"$job\"}[$interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_rw_in_bytes{job=\"$job\"}[$interval]))",
     "legendFormat": "overwrite"
    }
   ]
  },
  {
   "title": "$node - Network Traffic Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$cluster\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\", job=\"$cluster\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "$node - Network Traffic Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$cluster\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\", job=\"$cluster\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Objects increase Hourly",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(ceph_cluster_total_objects{job=\"$job\"}[1h]))",
     "legendFormat": "Objects"
    }
   ]
  },
  {
   "title": "Capacity increase Hourly",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum(increase(ceph_cluster_total_used_bytes{job=\"$job\"}[1h]))",
     "legendFormat": "Capacity"
    }
   ]
  },
  { "title": "OSD Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "OSD Storage Used",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{job=\"$job\"}",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "OSD Used %",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{job=\"$job\"}/ceph_osd_stat_bytes{job=\"$job\"}*100",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "RocksDB STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "job",
   "collapsed": true,
   "panels": [
    {
     "title": "BlueFS Log Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_bluefs_log_bytes{job=\"$job\"}",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "RocksDB GET",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(ceph_rocksdb_get{job=\"$job\"}[$interval]))",
       "legendFormat": "GET"
      }
     ]
    },
    {
     "title": "BlueFS DB %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ceph_bluefs_db_used_bytes{job=\"$job\"}/ceph_bluefs_db_total_bytes{job=\"$job\"}*100",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "BlueFS Slow DB %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ceph_bluefs_slow_used_bytes{job=\"$job\"}/ceph_bluefs_slow_total_bytes{job=\"$job\"}*100",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSD Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "1000*sum(increase(ceph_osd_op_r_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_r_latency_count{job=\"$job\"}[1m])),1)",
       "legendFormat": "read"
      },
      {
       "expr": "1000*sum(increase(ceph_osd_op_w_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_w_latency_count{job=\"$job\"}[1m])),1)",
       "legendFormat": "write"
      },
      {
       "expr": "1000*sum(increase(ceph_osd_op_rw_latency_sum{job=\"$job\"}[1m]))/clamp_min(sum(increase(ceph_osd_op_rw_latency_count{job=\"$job\"}[1m])),1)",
       "legendFormat": "overwrite"
      }
     ]
    },
    {
     "title": "OSD Apply Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ceph_osd_apply_latency_ms{job=\"$job\"}",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    },
    {
     "title": "OSD Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "ceph_osd_commit_latency_ms{job=\"$job\"}",
       "legendFormat": "{{ceph_daemon}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OBJECTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Objects in the Cluster",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ceph_cluster_total_objects{job=\"$job\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Objects Unfound / Degraded / Misplaced",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_num_objects_unfound{job=\"$job\"}",
       "legendFormat": "Unfound"
      },
      {
       "expr": "ceph_num_objects_degraded{job=\"$job\"}",
       "legendFormat": "Degraded"
      },
      {
       "expr": "ceph_num_objects_misplaced{job=\"$job\"}",
       "legendFormat": "Misplaced"
      }
     ]
    },
    {
     "title": "PGs",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_pg_active{job=\"$job\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "ceph_pg_clean{job=\"$job\"}",
       "legendFormat": "Clean"
      },
      {
       "expr": "ceph_pg_peering{job=\"$job\"}",
       "legendFormat": "Peering"
      },
      {
       "expr": "ceph_pg_degraded{job=\"$job\"}",
       "legendFormat": "Degraded"
      },
      {
       "expr": "ceph_pg_stale{job=\"$job\"}",
       "legendFormat": "Stale"
      },
      {
       "expr": "ceph_unclean_pgs{job=\"$job\"}",
       "legendFormat": "Unclean"
      },
      {
       "expr": "ceph_pg_undersized{job=\"$job\"}",
       "legendFormat": "Undersized"
      },
      {
       "expr": "ceph_pg_incomplete{job=\"$job\"}",
       "legendFormat": "Incomplete"
      },
      {
       "expr": "ceph_pg_forced_backfill{job=\"$job\"}",
       "legendFormat": "Forced Backfill"
      },
      {
       "expr": "ceph_pg_inconsistent{job=\"$job\"}",
       "legendFormat": "Inconsistent"
      },
      {
       "expr": "ceph_pg_forced_recovery{job=\"$job\"}",
       "legendFormat": "Forced Recovery"
      },
      {
       "expr": "ceph_pg_creating{job=\"$job\"}",
       "legendFormat": "Creating"
      },
      {
       "expr": "ceph_pg_wait_backfill{job=\"$job\"}",
       "legendFormat": "Wait Backfill"
      },
      {
       "expr": "ceph_pg_deep{job=\"$job\"}",
       "legendFormat": "Deep"
      },
      {
       "expr": "ceph_pg_scrubbing{job=\"$job\"}",
       "legendFormat": "Scrubbing"
      },
      {
       "expr": "ceph_pg_recovering{job=\"$job\"}",
       "legendFormat": "Recovering"
      },
      {
       "expr": "ceph_pg_repair{job=\"$job\"}",
       "legendFormat": "Repair"
      },
      {
       "expr": "ceph_pg_down{job=\"$job\"}",
       "legendFormat": "Down"
      },
      {
       "expr": "ceph_pg_peered{job=\"$job\"}",
       "legendFormat": "Peered"
      },
      {
       "expr": "ceph_pg_backfill{job=\"$job\"}",
       "legendFormat": "Backfill"
      },
      {
       "expr": "ceph_pg_remapped{job=\"$job\"}",
       "legendFormat": "Remapped"
      },
      {
       "expr": "ceph_pg_backfill_toofull{job=\"$job\"}",
       "legendFormat": "Backfill Toofull"
      }
     ]
    },
    {
     "title": "Faulty PGs",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceph_pg_degraded{job=\"$job\"}",
       "legendFormat": "Degraded"
      },
      {
       "expr": "ceph_pg_stale{job=\"$job\"}",
       "legendFormat": "Stale"
      },
      {
       "expr": "ceph_pg_undersized{job=\"$job\"}",
       "legendFormat": "Undersized"
      }
     ]
    },
    {
     "title": "Recovery Operations",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_recovery_ops{job=\"$job\"}[$interval]))",
       "legendFormat": "OPS"
      }
     ]
    }
   ]
  },
  {
   "title": "RGW STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "repeat": "job",
   "collapsed": true,
   "panels": [
    {
     "title": "RGW REQUEST",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(ceph_rgw_req{job=\"$job\"}[$interval]))",
       "legendFormat": "Req"
      }
     ]
    },
    {
     "title": "Cache Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(ceph_rgw_cache_hit{job=\"$job\"}[$interval]))",
       "legendFormat": "Hit"
      },
      {
       "expr": "sum(irate(ceph_rgw_cache_miss{job=\"$job\"}[$interval]))",
       "legendFormat": "Miss"
      }
     ]
    },
    {
     "title": "RadosGW QPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(ceph_rgw_get{job=\"$job\"}[$interval]))",
       "legendFormat": "GET"
      },
      {
       "expr": "sum(irate(ceph_rgw_put{job=\"$job\"}[$interval]))",
       "legendFormat": "PUT"
      }
     ]
    },
    {
     "title": "RadosGW ThroughPut",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(ceph_rgw_get_b{job=\"$job\"}[$interval]))",
       "legendFormat": "GET"
      },
      {
       "expr": "sum(irate(ceph_rgw_put_b{job=\"$job\"}[$interval]))",
       "legendFormat": "PUT"
      }
     ]
    }
   ]
  }
 ]
}